name: waiter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: 4.1.4
  get_storage: ^2.0.2
  shared_preferences: ^2.0.6
  auto_size_text: ^2.1.0
  url_launcher: ^6.0.3
  cached_network_image: ^3.0.0
  fl_chart: ^0.35.0
  progress_dialog: ^1.2.4
  connectivity: ^3.0.6
  lazy_load_scrollview: ^1.3.0
  device_preview: ^0.7.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/welcome.png
    - assets/images/waiter_img.png
    - assets/images/burger_1.jpg
    - assets/images/launcher_icon.png
    - assets/images/res_table.jpg
    - assets/img/brazil.png
    - assets/img/canada.png
    - assets/img/china.png
    - assets/img/france.png
    - assets/img/germany.png
    - assets/img/italy.png
    - assets/img/netherlands.png
    - assets/img/spain.png
    - assets/img/united-arab-emirates.png
    - assets/img/united-states-of-america.png
    - assets/img/marker.png
    - assets/img/my_marker.png
    - assets/img/logo.png
    - assets/img/loading.gif
    - assets/img/whatsapp.png
    - assets/img/box.jpg
    - assets/img/verify_email_icon.jpg
    - assets/img/buy_something.jpg
    - assets/img/delivery_car_img.png
    - assets/img/fmd_good_marker.png
    - assets/img/camera_img.png
    - assets/img/gallery_img.jpg
    - assets/img/location_img.png
    - assets/img/destination_map.png
    - assets/img/car.png
    - assets/img/googlemap.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages